#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArmWreslingPanelComponent_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OPP_structs.hpp"
#include "OPP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ArmWreslingPanelComponent_BP.ArmWreslingPanelComponent_BP_C
// 0x0010 (0x0960 - 0x0950)
class UArmWreslingPanelComponent_BP_C final : public URBArmWreslingPanelComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0950(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ArmWreslingPanelComponent_BP(int32 EntryPoint);
	void OnPawnSpecialMoveStarted(class ARBPawn* Pawn, ESpecialMove SpecialMove);
	void CustomEvent_0(const struct FArmWreslingPlayerRoundData& PlayerRoundData);
	void OnLinkedTableChange();

	bool GetInteractionPawnLocation(const class ARBPawn* Pawn, ESpecialMove SpecialMove, struct FVector* OutLocation, struct FVector* OutDirection) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ArmWreslingPanelComponent_BP_C">();
	}
	static class UArmWreslingPanelComponent_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArmWreslingPanelComponent_BP_C>();
	}
};
static_assert(alignof(UArmWreslingPanelComponent_BP_C) == 0x000010, "Wrong alignment on UArmWreslingPanelComponent_BP_C");
static_assert(sizeof(UArmWreslingPanelComponent_BP_C) == 0x000960, "Wrong size on UArmWreslingPanelComponent_BP_C");
static_assert(offsetof(UArmWreslingPanelComponent_BP_C, UberGraphFrame) == 0x000950, "Member 'UArmWreslingPanelComponent_BP_C::UberGraphFrame' has a wrong offset!");

}

