#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CeilingFluorescentMinus05

#include "Basic.hpp"

#include "CeilingFluorescentLightBaseMinus01_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CeilingFluorescent-05.CeilingFluorescent-05_C
// 0x0010 (0x0780 - 0x0770)
class ACeilingFluorescentMinus05_C final : public ACeilingFluorescentLightBaseMinus01_C
{
public:
	struct FVector                                SlineTangent;                                      // 0x0768(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CeilingFluorescent-05_C">();
	}
	static class ACeilingFluorescentMinus05_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACeilingFluorescentMinus05_C>();
	}
};
static_assert(alignof(ACeilingFluorescentMinus05_C) == 0x000010, "Wrong alignment on ACeilingFluorescentMinus05_C");
static_assert(sizeof(ACeilingFluorescentMinus05_C) == 0x000780, "Wrong size on ACeilingFluorescentMinus05_C");
static_assert(offsetof(ACeilingFluorescentMinus05_C, SlineTangent) == 0x000768, "Member 'ACeilingFluorescentMinus05_C::SlineTangent' has a wrong offset!");

}

