#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterSheetBadgesTab

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "Slate_structs.hpp"
#include "OPP_structs.hpp"
#include "AkAudio_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.HandleInputSourceChanged
// 0x0004 (0x0004 - 0x0000)
struct CharacterSheetBadgesTab_C_HandleInputSourceChanged final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EScrollWhenFocusChanges                       Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EScrollWhenFocusChanges                       Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EScrollWhenFocusChanges                       K2Node_Select_Default;                             // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CharacterSheetBadgesTab_C_HandleInputSourceChanged) == 0x000001, "Wrong alignment on CharacterSheetBadgesTab_C_HandleInputSourceChanged");
static_assert(sizeof(CharacterSheetBadgesTab_C_HandleInputSourceChanged) == 0x000004, "Wrong size on CharacterSheetBadgesTab_C_HandleInputSourceChanged");
static_assert(offsetof(CharacterSheetBadgesTab_C_HandleInputSourceChanged, Temp_bool_Variable) == 0x000000, "Member 'CharacterSheetBadgesTab_C_HandleInputSourceChanged::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_HandleInputSourceChanged, Temp_byte_Variable) == 0x000001, "Member 'CharacterSheetBadgesTab_C_HandleInputSourceChanged::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_HandleInputSourceChanged, Temp_byte_Variable_1) == 0x000002, "Member 'CharacterSheetBadgesTab_C_HandleInputSourceChanged::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_HandleInputSourceChanged, K2Node_Select_Default) == 0x000003, "Member 'CharacterSheetBadgesTab_C_HandleInputSourceChanged::K2Node_Select_Default' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.Claim
// 0x0030 (0x0030 - 0x0000)
struct CharacterSheetBadgesTab_C_Claim final
{
public:
	TDelegate<void(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo)> Temp_delegate_Variable;                            // 0x0000(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	int32                                         CallFunc_PostEventGlobal_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33C9[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URBMenuWithTabsWidget*                  CallFunc_GetMenuWithTabsParent_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCharacterSheet_C*                      K2Node_DynamicCast_AsCharacter_Sheet;              // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue;          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CharacterSheetBadgesTab_C_Claim) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_Claim");
static_assert(sizeof(CharacterSheetBadgesTab_C_Claim) == 0x000030, "Wrong size on CharacterSheetBadgesTab_C_Claim");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, Temp_delegate_Variable) == 0x000000, "Member 'CharacterSheetBadgesTab_C_Claim::Temp_delegate_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, CallFunc_PostEventGlobal_ReturnValue) == 0x000010, "Member 'CharacterSheetBadgesTab_C_Claim::CallFunc_PostEventGlobal_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, CallFunc_GetMenuWithTabsParent_ReturnValue) == 0x000018, "Member 'CharacterSheetBadgesTab_C_Claim::CallFunc_GetMenuWithTabsParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, K2Node_DynamicCast_AsCharacter_Sheet) == 0x000020, "Member 'CharacterSheetBadgesTab_C_Claim::K2Node_DynamicCast_AsCharacter_Sheet' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'CharacterSheetBadgesTab_C_Claim::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Claim, CallFunc_CanClaimBadgeReward_ReturnValue) == 0x000029, "Member 'CharacterSheetBadgesTab_C_Claim::CallFunc_CanClaimBadgeReward_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.BuildBadgeRewards
// 0x0120 (0x0120 - 0x0000)
struct CharacterSheetBadgesTab_C_BuildBadgeRewards final
{
public:
	class FName                                   RewardDataId;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bClaimable;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bUnlockedAtLeastOnce;                              // 0x0009(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33CA[0x6];                                     // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UProgramTrialBlockWidget_C*             CurrentProgramBlockWidget;                         // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33CB[0x1];                                     // 0x001F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UProgramTrialRewardWidget_C*            CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33CC[0x3];                                     // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33CD[0x6];                                     // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARBPlayerState*                         CallFunc_GetLocalPlayerState_ReturnValue;          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URBPlayerProgressionData*               CallFunc_GetLocalPlayerProgressionData_ReturnValue; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRBRewardData                          CallFunc_GetRewardData_ReturnValue;                // 0x0058(0x0088)(ConstParm)
	TArray<struct FRewardUIData>                  CallFunc_GetRewardUIDataFromRewards_ReturnValue;   // 0x00E0(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33CE[0x4];                                     // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRewardUIData                          CallFunc_Array_Get_Item;                           // 0x00F8(0x0020)(NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CharacterSheetBadgesTab_C_BuildBadgeRewards) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_BuildBadgeRewards");
static_assert(sizeof(CharacterSheetBadgesTab_C_BuildBadgeRewards) == 0x000120, "Wrong size on CharacterSheetBadgesTab_C_BuildBadgeRewards");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, RewardDataId) == 0x000000, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::RewardDataId' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, bClaimable) == 0x000008, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::bClaimable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, bUnlockedAtLeastOnce) == 0x000009, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::bUnlockedAtLeastOnce' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CurrentProgramBlockWidget) == 0x000010, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CurrentProgramBlockWidget' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_byte_Variable) == 0x000018, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Not_PreBool_ReturnValue) == 0x000019, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_BooleanOR_ReturnValue) == 0x00001A, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_byte_Variable_1) == 0x00001B, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_bool_Variable) == 0x00001C, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_byte_Variable_2) == 0x00001D, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_byte_Variable_3) == 0x00001E, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Create_ReturnValue) == 0x000020, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, K2Node_Select_Default) == 0x000028, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_int_Array_Index_Variable) == 0x00002C, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_int_Loop_Counter_Variable) == 0x000030, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Add_IntInt_ReturnValue) == 0x000034, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, Temp_bool_Variable_1) == 0x000038, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, K2Node_Select_Default_1) == 0x000039, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000040, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_GetLocalPlayerState_ReturnValue) == 0x000048, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_GetLocalPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_GetLocalPlayerProgressionData_ReturnValue) == 0x000050, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_GetLocalPlayerProgressionData_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_GetRewardData_ReturnValue) == 0x000058, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_GetRewardData_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_GetRewardUIDataFromRewards_ReturnValue) == 0x0000E0, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_GetRewardUIDataFromRewards_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Array_Length_ReturnValue) == 0x0000F0, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Array_Get_Item) == 0x0000F8, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_BuildBadgeRewards, CallFunc_Less_IntInt_ReturnValue) == 0x000118, "Member 'CharacterSheetBadgesTab_C_BuildBadgeRewards::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.SetupHoveredBadge
// 0x0178 (0x0178 - 0x0000)
struct CharacterSheetBadgesTab_C_SetupHoveredBadge final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33CF[0x6];                                     // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0018)()
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D0[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0028(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0068(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue_1;        // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D1[0x7];                                     // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00B0(0x0010)(ReferenceParm)
	int32                                         CallFunc_GetBadgeProgress_ReturnValue;             // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33D2[0x4];                                     // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00C8(0x0018)()
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBadgeUnlockCount_ReturnValue;          // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x00E8(0x0018)()
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D3[0x7];                                     // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0108(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0148(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0158(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CharacterSheetBadgesTab_C_SetupHoveredBadge) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_SetupHoveredBadge");
static_assert(sizeof(CharacterSheetBadgesTab_C_SetupHoveredBadge) == 0x000178, "Wrong size on CharacterSheetBadgesTab_C_SetupHoveredBadge");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, Temp_byte_Variable) == 0x000000, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, Temp_byte_Variable_1) == 0x000001, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_Conv_IntToText_ReturnValue) == 0x000008, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_CanClaimBadgeReward_ReturnValue) == 0x000020, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_CanClaimBadgeReward_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_MakeStruct_FormatArgumentData) == 0x000028, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_MakeStruct_FormatArgumentData_1) == 0x000068, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_CanClaimBadgeReward_ReturnValue_1) == 0x0000A8, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_CanClaimBadgeReward_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_MakeArray_Array) == 0x0000B0, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_GetBadgeProgress_ReturnValue) == 0x0000C0, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_GetBadgeProgress_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_Format_ReturnValue) == 0x0000C8, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_SelectInt_ReturnValue) == 0x0000E0, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_GetBadgeUnlockCount_ReturnValue) == 0x0000E4, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_GetBadgeUnlockCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_Conv_IntToText_ReturnValue_1) == 0x0000E8, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_Greater_IntInt_ReturnValue) == 0x000100, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_MakeStruct_FormatArgumentData_2) == 0x000108, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_MakeArray_Array_1) == 0x000148, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, CallFunc_Format_ReturnValue_1) == 0x000158, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, Temp_bool_Variable) == 0x000170, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupHoveredBadge, K2Node_Select_Default) == 0x000171, "Member 'CharacterSheetBadgesTab_C_SetupHoveredBadge::K2Node_Select_Default' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.SetupSelectedBadge
// 0x0190 (0x0190 - 0x0000)
struct CharacterSheetBadgesTab_C_SetupSelectedBadge final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33D4[0x5];                                     // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0008(0x0018)()
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0028(0x0018)()
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33D5[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0048(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0088(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue;          // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D6[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D0(0x0010)(ReferenceParm)
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue_1;        // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D7[0x7];                                     // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E8(0x0018)()
	int32                                         CallFunc_GetBadgeUnlockCount_ReturnValue;          // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBadgeProgress_ReturnValue;             // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D8[0x3];                                     // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0110(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0128(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0168(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0178(0x0018)()
};
static_assert(alignof(CharacterSheetBadgesTab_C_SetupSelectedBadge) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_SetupSelectedBadge");
static_assert(sizeof(CharacterSheetBadgesTab_C_SetupSelectedBadge) == 0x000190, "Wrong size on CharacterSheetBadgesTab_C_SetupSelectedBadge");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, Temp_bool_Variable) == 0x000000, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, Temp_byte_Variable) == 0x000001, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, Temp_byte_Variable_1) == 0x000002, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_MakeLiteralText_ReturnValue) == 0x000008, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_MakeLiteralName_ReturnValue) == 0x000020, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_Conv_IntToText_ReturnValue) == 0x000028, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_Select_Default) == 0x000040, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_MakeStruct_FormatArgumentData) == 0x000048, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_MakeStruct_FormatArgumentData_1) == 0x000088, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_CanClaimBadgeReward_ReturnValue) == 0x0000C8, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_CanClaimBadgeReward_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_MakeArray_Array) == 0x0000D0, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_CanClaimBadgeReward_ReturnValue_1) == 0x0000E0, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_CanClaimBadgeReward_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_Format_ReturnValue) == 0x0000E8, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_GetBadgeUnlockCount_ReturnValue) == 0x000100, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_GetBadgeUnlockCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_GetBadgeProgress_ReturnValue) == 0x000104, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_GetBadgeProgress_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_Greater_IntInt_ReturnValue) == 0x000108, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_SelectInt_ReturnValue) == 0x00010C, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000110, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_MakeStruct_FormatArgumentData_2) == 0x000128, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, K2Node_MakeArray_Array_1) == 0x000168, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_SetupSelectedBadge, CallFunc_Format_ReturnValue_1) == 0x000178, "Member 'CharacterSheetBadgesTab_C_SetupSelectedBadge::CallFunc_Format_ReturnValue_1' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.OnFocusReceived
// 0x01C0 (0x01C0 - 0x0000)
struct CharacterSheetBadgesTab_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33D9[0x7];                                     // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0108(0x00B8)()
};
static_assert(alignof(CharacterSheetBadgesTab_C_OnFocusReceived) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_OnFocusReceived");
static_assert(sizeof(CharacterSheetBadgesTab_C_OnFocusReceived) == 0x0001C0, "Wrong size on CharacterSheetBadgesTab_C_OnFocusReceived");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, InFocusEvent) == 0x000038, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, ReturnValue) == 0x000040, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, CallFunc_GetChildAt_ReturnValue) == 0x0000F8, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, CallFunc_IsValid_ReturnValue) == 0x000100, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnFocusReceived, CallFunc_Handled_ReturnValue) == 0x000108, "Member 'CharacterSheetBadgesTab_C_OnFocusReceived::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.OnBadgeClicked
// 0x0010 (0x0010 - 0x0000)
struct CharacterSheetBadgesTab_C_OnBadgeClicked final
{
public:
	class UBadgeSashEntry_C*                      badgeEntry;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CharacterSheetBadgesTab_C_OnBadgeClicked) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_OnBadgeClicked");
static_assert(sizeof(CharacterSheetBadgesTab_C_OnBadgeClicked) == 0x000010, "Wrong size on CharacterSheetBadgesTab_C_OnBadgeClicked");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeClicked, badgeEntry) == 0x000000, "Member 'CharacterSheetBadgesTab_C_OnBadgeClicked::badgeEntry' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeClicked, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'CharacterSheetBadgesTab_C_OnBadgeClicked::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.OnBadgeUnhovered
// 0x0010 (0x0010 - 0x0000)
struct CharacterSheetBadgesTab_C_OnBadgeUnhovered final
{
public:
	class UBadgeSashEntry_C*                      badgeEntry;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0008(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CharacterSheetBadgesTab_C_OnBadgeUnhovered) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_OnBadgeUnhovered");
static_assert(sizeof(CharacterSheetBadgesTab_C_OnBadgeUnhovered) == 0x000010, "Wrong size on CharacterSheetBadgesTab_C_OnBadgeUnhovered");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeUnhovered, badgeEntry) == 0x000000, "Member 'CharacterSheetBadgesTab_C_OnBadgeUnhovered::badgeEntry' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeUnhovered, CallFunc_K2_SetTimer_ReturnValue) == 0x000008, "Member 'CharacterSheetBadgesTab_C_OnBadgeUnhovered::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.OnBadgeHovered
// 0x0010 (0x0010 - 0x0000)
struct CharacterSheetBadgesTab_C_OnBadgeHovered final
{
public:
	class UBadgeSashEntry_C*                      badgeEntry;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CharacterSheetBadgesTab_C_OnBadgeHovered) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_OnBadgeHovered");
static_assert(sizeof(CharacterSheetBadgesTab_C_OnBadgeHovered) == 0x000010, "Wrong size on CharacterSheetBadgesTab_C_OnBadgeHovered");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeHovered, badgeEntry) == 0x000000, "Member 'CharacterSheetBadgesTab_C_OnBadgeHovered::badgeEntry' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_OnBadgeHovered, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'CharacterSheetBadgesTab_C_OnBadgeHovered::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.Refresh Badges
// 0x0170 (0x0170 - 0x0000)
struct CharacterSheetBadgesTab_C_Refresh_Badges final
{
public:
	class UBadgeSashEntry_C*                      PreviouslySelectedBadge;                           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRBPlayerBadgeRow                      CurrentBadgeInfo;                                  // 0x0008(0x00A8)(Edit, BlueprintVisible)
	int32                                         BadgesPerRow;                                      // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33DA[0x4];                                     // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBadgeSashEntry_C*                      K2Node_DynamicCast_AsBadge_Sash_Entry;             // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanClaimBadgeReward_ReturnValue;          // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33DB[0x1];                                     // 0x00D3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetBadgeUnlockCount_ReturnValue;          // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBadgeSashEntry_C*                      CallFunc_Create_ReturnValue;                       // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33DC[0x7];                                     // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URBPlayerProgressionData*               CallFunc_GetLocalPlayerProgressionData_ReturnValue; // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UBadgeSashEntry_C* badgeEntry)> K2Node_CreateDelegate_OutputDelegate;              // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FRBPlayerBadgeRow>              CallFunc_GetBadges_ReturnValue;                    // 0x0100(0x0010)(ReferenceParm)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Divide_IntInt_ReturnValue;                // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URBPlayerProgressionData*               CallFunc_GetLocalPlayerProgressionData_ReturnValue_1; // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUniformGridSlot*                       CallFunc_AddChildToUniformGrid_ReturnValue;        // 0x0120(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FRBPlayerBadgeRow>              CallFunc_GetBadges_ReturnValue_1;                  // 0x0128(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UBadgeSashEntry_C* badgeEntry)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0140(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33DD[0x3];                                     // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UBadgeSashEntry_C* badgeEntry)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0154(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0164(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33DE[0x3];                                     // 0x0165(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UBadgeSashEntry_C*                      K2Node_Select_Default;                             // 0x0168(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CharacterSheetBadgesTab_C_Refresh_Badges) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_Refresh_Badges");
static_assert(sizeof(CharacterSheetBadgesTab_C_Refresh_Badges) == 0x000170, "Wrong size on CharacterSheetBadgesTab_C_Refresh_Badges");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, PreviouslySelectedBadge) == 0x000000, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::PreviouslySelectedBadge' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CurrentBadgeInfo) == 0x000008, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CurrentBadgeInfo' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, BadgesPerRow) == 0x0000B0, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::BadgesPerRow' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, Temp_int_Variable) == 0x0000B4, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Add_IntInt_ReturnValue) == 0x0000B8, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetChildAt_ReturnValue) == 0x0000C0, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_DynamicCast_AsBadge_Sash_Entry) == 0x0000C8, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_DynamicCast_AsBadge_Sash_Entry' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_DynamicCast_bSuccess) == 0x0000D0, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_IsValid_ReturnValue) == 0x0000D1, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_CanClaimBadgeReward_ReturnValue) == 0x0000D2, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_CanClaimBadgeReward_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetBadgeUnlockCount_ReturnValue) == 0x0000D4, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetBadgeUnlockCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Create_ReturnValue) == 0x0000D8, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_EqualEqual_NameName_ReturnValue) == 0x0000E0, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetLocalPlayerProgressionData_ReturnValue) == 0x0000E8, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetLocalPlayerProgressionData_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_CreateDelegate_OutputDelegate) == 0x0000F0, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetBadges_ReturnValue) == 0x000100, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetBadges_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Percent_IntInt_ReturnValue) == 0x000110, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Divide_IntInt_ReturnValue) == 0x000114, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Divide_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetLocalPlayerProgressionData_ReturnValue_1) == 0x000118, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetLocalPlayerProgressionData_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_AddChildToUniformGrid_ReturnValue) == 0x000120, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_AddChildToUniformGrid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_GetBadges_ReturnValue_1) == 0x000128, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_GetBadges_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Array_Length_ReturnValue) == 0x000138, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_Subtract_IntInt_ReturnValue) == 0x00013C, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_CreateDelegate_OutputDelegate_1) == 0x000140, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000150, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_CreateDelegate_OutputDelegate_2) == 0x000154, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, Temp_bool_Variable) == 0x000164, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_Refresh_Badges, K2Node_Select_Default) == 0x000168, "Member 'CharacterSheetBadgesTab_C_Refresh_Badges::K2Node_Select_Default' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.ExecuteUbergraph_CharacterSheetBadgesTab
// 0x0028 (0x0028 - 0x0000)
struct CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_33DF[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URBMenuManager*                         CallFunc_GetMenuManager_ReturnValue;               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BP_IsUsingGamepad_ReturnValue;            // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab");
static_assert(sizeof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab) == 0x000028, "Wrong size on CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, EntryPoint) == 0x000000, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, CallFunc_GetMenuManager_ReturnValue) == 0x000018, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::CallFunc_GetMenuManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, CallFunc_IsValid_ReturnValue_1) == 0x000021, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab, CallFunc_BP_IsUsingGamepad_ReturnValue) == 0x000022, "Member 'CharacterSheetBadgesTab_C_ExecuteUbergraph_CharacterSheetBadgesTab::CallFunc_BP_IsUsingGamepad_ReturnValue' has a wrong offset!");

// Function CharacterSheetBadgesTab.CharacterSheetBadgesTab_C.GetPageTitle
// 0x0018 (0x0018 - 0x0000)
struct CharacterSheetBadgesTab_C_GetPageTitle final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(CharacterSheetBadgesTab_C_GetPageTitle) == 0x000008, "Wrong alignment on CharacterSheetBadgesTab_C_GetPageTitle");
static_assert(sizeof(CharacterSheetBadgesTab_C_GetPageTitle) == 0x000018, "Wrong size on CharacterSheetBadgesTab_C_GetPageTitle");
static_assert(offsetof(CharacterSheetBadgesTab_C_GetPageTitle, ReturnValue) == 0x000000, "Member 'CharacterSheetBadgesTab_C_GetPageTitle::ReturnValue' has a wrong offset!");

}

